### ISSUE TITLE
merge this project with node-nanomsg

### ISSUE THREAD

**Issue by reqshark** [reqshark/nanomsg.iojs#19]
planning to move this repo into the official nanomsg binding for node, discussions began here https://github.com/nickdesaulniers/node-nanomsg/issues/44

cc: @nickdesaulniers

**Comment by nickdesaulniers** [comment]
I think we could use [this](https://github.com/substack/emit-stream) to provide a callback and streams based API.  Not sure of the implications or incompatibilities, but :+1: code reuse.

**Comment by reqshark** [comment]
ya that's a cool project. of course streams inherit from `EventEmitter`, but with a few special custom events. that's basically a stream in a nutshell.

Unfortunately not all of those events/functions on node's `require('stream')` class over the [years are consistent across major releases](https://github.com/joyent/node/blob/master/doc/api/stream.markdown#compatibility-with-older-node-versions), for example, node 0.8 lacks base classes: Readable, Writable, Duplex, and Transform, see e.g., https://github.com/joyent/node/wiki/API-changes-between-v0.8-and-v0.10

in general, so long as we're inheriting from Isaac's [`readable-stream`](https://github.com/iojs/readable-stream) we should be safely implementing consistent stream interfaces across node versions up through the latest `iojs` release. 

However, I've experienced problems using that technique on node 0.8 due to NPM not being able to pull in dependencies listed in package.json. I'm sure there's a nice way to fix it, I think probably pinning a slightly older version of `readable-stream` if we want to support node 0.8. otherwise we can probably just decide at the outset not to support node 0.8.

**Comment by reqshark** [comment]
i think if https://github.com/nickdesaulniers/node-nanomsg/pull/53 is merged, i can close this one

**Comment by nickdesaulniers** [comment]
fixed!

**Comment by reqshark** [comment]
closed by https://github.com/nickdesaulniers/node-nanomsg/commit/cf3242519b65ca3078a4fac416b4901ccf99c781
