### ISSUE TITLE
nanomsg review

### ISSUE THREAD

**Issue by reqshark** [reqshark/nanomsg.iojs#4]
@ronkorving, hey i created this nanomsg.iojs project a few weeks ago. I plan to keep up with nanomsg upstream and want to optimize this for sending and receiving next level pluggable protocol msgs. (afterall nanomsg was Martin Sustrik's improved redesign after creating ZeroMQ)

Mind you, there's also [node-nanomsg](https://github.com/nickdesaulniers/node-nanomsg), a super well written project and a lot more complete than this one. I think node-nanomsg leverages a notably different approach to a node/iojs binding with really sweet perf there as a result. 

I hope you might be interested, so take a look and always feel free to review, moderate, merge, revert, commit etc., you've been invited with write access because of how much i trust your judgment

**Comment by ronkorving** [comment]
Hi @reqshark, thanks for the access!

Weird question perhaps (or maybe not), but given node-nanomsg, why did you bother to create this? :)

**Comment by reqshark** [comment]
@ronkorving no doubt.  

that's a good question! I want to call the system kernel API directly with select and poll operations on the socket and experiment with a custom event mechanism around that. I've only just started building that here: https://github.com/reqshark/nanomsg.iojs/blob/master/lib/getevents.h

Also I noticed that the `setsockopt()` and `getsockopt()` API (well.. i mean the function signature) of ZeroMQ and Nanomsg is identical. While I think, in terms of interfacing from a binding, that part of the library ABIs has improved since ZeroMQ, it's still akward and painful to work with from my JavaScript perspective.  I want to fix this because there's a ton of useful performance configurations that have been built in and around this ABI. In Nanomsg I've found that you can really tune sockets and the differences, like for example, when you disable naggle's algoirthm with `NN_TCP_NODELAY` are simply too substantial to ignore. My idea is pass all of our opts as a config object at the start of the socket and to be able to really do that right would be a huge PR on node-nanomsg. 

Also I want to use the latest versions of libnanomsg (beta 5 and the upcoming beta 6) because there's active work on the websocket type. So it would be like let's just set up a `socket('ws')` for sending messages over websocket, and that would tie more easily in with browser dev... or maybe just `pipe()` to [websocket-stream](https://github.com/maxogden/websocket-stream) 

but the biggest reason is that i wanted to get better at writing node binding code and to experiment and learn

**Comment by reqshark** [comment]
oh also I wanted to see if you could write this type of thing in JavaScript without accessing the protoype property directly

**Comment by reqshark** [comment]
@kkoopa invited for the same reason above

**Comment by nickdesaulniers** [comment]
This work should be upstreamed into node-nanomsg.  I'm happy to dole out commit bits as needed.  I don't see why the custom event loop cant be in an experimental branch until we can weigh the benefits and deficits.  Otherwise, there's a lot of duplication of effort, and adds to the problem of node having too many packages that do similar things and users being confused as to which module to choose.

**Comment by reqshark** [comment]
ya i agree, some of the higher level API, the setsockopt API here could probably get chunked into a PR on master without getting into the low level stuff. I'm actually using your C/C++ for that particular part under the hood: https://github.com/reqshark/nanomsg.iojs/blob/master/lib/nanomsg.cc#L53-L85 so it's fully compatible right now. 

i'll start sending some PRs in the coming days probably over this weekend especially.. and @nickdesaulniers can you publish a branch for me on node-nanomsg where we can compare different i/o multiplexing strategies. ideally we want run the latency and throughput tests to figure out which is best.. we need to compare apples and apples and run the branches side by side to observe meaningful performance results

**Comment by nickdesaulniers** [comment]
https://github.com/nickdesaulniers/node-nanomsg/tree/custom-event-loop

**Comment by reqshark** [comment]
closed by https://github.com/nickdesaulniers/node-nanomsg/commit/cf3242519b65ca3078a4fac416b4901ccf99c781
